import "server-only";
import PDFDocument from "pdfkit";
import { prismaUnsafe } from "@/lib/db/prisma";
import { formatIST } from "@/lib/format/date";

/**
 * Shared PDF chrome for all reports — header band + footer rule.
 *
 * Each report module calls `openReportPdf({ organisationId, title })`,
 * receives a `doc` already positioned below the header band, fills its
 * body, then calls `closeReportPdf(doc)` which stamps the footer and
 * returns the buffer.
 *
 * Mirrors the visual conventions of the 80G receipt + 10BE certificate:
 *   - Thin primary-green accent strip at the top
 *   - Centred org name + address
 *   - Title in primary-green with letter-spacing, bookended by hairlines
 *   - Period subtitle below the title
 *   - Footer rule + computer-generated note
 */

const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;
const MARGIN = 48;
const CONTENT_WIDTH = A4_WIDTH - MARGIN * 2;

const COLORS = {
  ink: "#1A1814",
  inkMuted: "#5C5852",
  inkSubtle: "#8A857E",
  primary: "#1A6E5A",
  primarySoft: "#E8F0ED",
  border: "#E8E3D9",
  borderStrong: "#D4CEC2",
} as const;

export type ReportPdfHandle = {
  doc: InstanceType<typeof PDFDocument>;
  /** y-coordinate the body should start drawing from. */
  bodyTop: number;
  margin: number;
  contentWidth: number;
  colors: typeof COLORS;
  orgName: string;
};

export async function openReportPdf(input: {
  organisationId: string;
  title: string;
  periodLabel: string;
}): Promise<{
  handle: ReportPdfHandle;
  finish(): Promise<Buffer>;
}> {
  const org = await prismaUnsafe.organisation.findUniqueOrThrow({
    where: { id: input.organisationId },
  });

  const doc = new PDFDocument({
    size: "A4",
    margin: MARGIN,
    info: { Title: input.title },
  });
  const chunks: Buffer[] = [];
  doc.on("data", (c) => chunks.push(c as Buffer));

  // ===== Accent strip + header =====
  doc.rect(0, 0, A4_WIDTH, 6).fillColor(COLORS.primary).fill();

  const headerTop = MARGIN + 8;
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(COLORS.ink)
    .text(org.legalName ?? org.name, MARGIN, headerTop + 4, {
      width: CONTENT_WIDTH,
      align: "center",
      characterSpacing: 0.4,
    });
  const addressLine = [
    org.addressLine1,
    [org.city, org.state, org.pincode].filter(Boolean).join(" "),
  ]
    .filter(Boolean)
    .join(", ");
  if (addressLine) {
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor(COLORS.inkMuted)
      .text(addressLine, MARGIN, doc.y + 3, {
        width: CONTENT_WIDTH,
        align: "center",
      });
  }
  if (org.pan) {
    doc
      .fontSize(8)
      .fillColor(COLORS.inkSubtle)
      .text(`PAN ${org.pan}`, MARGIN, doc.y + 2, {
        width: CONTENT_WIDTH,
        align: "center",
      });
  }

  // Title block — hairlines + primary-coloured title + period subtitle
  const titleTop = doc.y + 18;
  doc
    .moveTo(MARGIN, titleTop)
    .lineTo(MARGIN + CONTENT_WIDTH, titleTop)
    .lineWidth(0.4)
    .strokeColor(COLORS.borderStrong)
    .stroke();
  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .fillColor(COLORS.primary)
    .text(input.title.toUpperCase(), MARGIN, titleTop + 12, {
      width: CONTENT_WIDTH,
      align: "center",
      characterSpacing: 2,
    });
  doc
    .font("Helvetica-Oblique")
    .fontSize(10)
    .fillColor(COLORS.inkMuted)
    .text(input.periodLabel, MARGIN, doc.y + 2, {
      width: CONTENT_WIDTH,
      align: "center",
    });
  const titleBottom = doc.y + 8;
  doc
    .moveTo(MARGIN, titleBottom)
    .lineTo(MARGIN + CONTENT_WIDTH, titleBottom)
    .lineWidth(0.4)
    .strokeColor(COLORS.borderStrong)
    .stroke();

  const bodyTop = titleBottom + 16;
  // Reset cursor to body position so the report module starts drawing here.
  doc.y = bodyTop;

  const handle: ReportPdfHandle = {
    doc,
    bodyTop,
    margin: MARGIN,
    contentWidth: CONTENT_WIDTH,
    colors: COLORS,
    orgName: org.legalName ?? org.name,
  };

  return {
    handle,
    finish(): Promise<Buffer> {
      // ===== Footer =====
      const footerRuleY = A4_HEIGHT - MARGIN - 28;
      doc
        .moveTo(MARGIN, footerRuleY)
        .lineTo(MARGIN + CONTENT_WIDTH, footerRuleY)
        .lineWidth(0.4)
        .strokeColor(COLORS.border)
        .stroke();
      doc
        .font("Helvetica")
        .fontSize(8)
        .fillColor(COLORS.inkSubtle)
        .text(
          `Generated by Rakshana on ${formatIST(new Date(), "dd MMM yyyy")}${org.email ? ` · Verify with ${org.email}` : ""}`,
          MARGIN,
          footerRuleY + 6,
          { width: CONTENT_WIDTH, align: "center" },
        );

      return new Promise<Buffer>((resolve, reject) => {
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);
        doc.end();
      });
    },
  };
}

/**
 * Convenience helper: draw a 2-column "key/value" block where the right
 * column is right-aligned and tabular-num for money. Used by most reports.
 */
export function drawKvRows(
  handle: ReportPdfHandle,
  rows: { label: string; value: string; emphasis?: boolean }[],
  opts: { startY?: number; rowHeight?: number } = {},
): number {
  const { doc, margin, contentWidth, colors } = handle;
  const rowHeight = opts.rowHeight ?? 18;
  let y = opts.startY ?? doc.y;
  for (const r of rows) {
    doc
      .font(r.emphasis ? "Helvetica-Bold" : "Helvetica")
      .fontSize(10)
      .fillColor(r.emphasis ? colors.ink : colors.inkMuted)
      .text(r.label, margin, y, { width: contentWidth / 2 });
    doc
      .font(r.emphasis ? "Helvetica-Bold" : "Helvetica")
      .fontSize(10)
      .fillColor(colors.ink)
      .text(r.value, margin + contentWidth / 2, y, {
        width: contentWidth / 2,
        align: "right",
      });
    y += rowHeight;
  }
  doc.y = y;
  return y;
}

/** Section heading with a thin underline. */
export function drawSectionHeading(
  handle: ReportPdfHandle,
  text: string,
  startY?: number,
): void {
  const { doc, margin, contentWidth, colors } = handle;
  const y = startY ?? doc.y;
  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(colors.primary)
    .text(text.toUpperCase(), margin, y, {
      characterSpacing: 1.5,
    });
  const ruleY = doc.y + 2;
  doc
    .moveTo(margin, ruleY)
    .lineTo(margin + contentWidth, ruleY)
    .lineWidth(0.3)
    .strokeColor(colors.borderStrong)
    .stroke();
  doc.y = ruleY + 8;
}
